#! /bin/bash
#
# global find replace for our project, to help with refactoring ...
#
# usage: ./find_replace 'find this' 'replace with this'
#
if [[ -z "$1" ]] || [[ -z "$2" ]] ; then
	echo "usage:    $0 'find this' 'replace with this'"
	exit
fi

FIND="$1"
REPLACE="$2"
NOW="$(date +%Y%m%d_%H%M%S)"

echo -e "\nsearching for instances of: '$FIND' ... \n"
FOUND=$(grep -rio "$FIND" . | sed 's/:.*//g' | sed 's/^.\///g' | grep -v '^tmp' | grep -v '^.git' | grep -v 'Binary file' | uniq)
echo -e "found: -------------- \n${FOUND}\n ---------------------"

echo -e "\nreplacing '$FIND' in these files with '$REPLACE' ... \n"
for file in $FOUND; do
	without_slashes=$(echo "$file" | sed 's/\//_/g' | sed 's/\./-/g')
	temp_file="tmp/$without_slashes.find_replace.$NOW"
	echo "cp $file $temp_file"
#	cp $file $temp_file
	echo "cat $temp_file | sed 's/$FIND/$REPLACE/g' > $file"
#	if [[ -f "$temp_file" ]] ; then
#		cat $temp_file | sed "s/$FIND/$REPLACE/g" > $file
#	else
#		echo "File was not created ? $temp_file"
#	fi
done
echo -e "\ndone!\n"

echo "re-searching to see if '$FIND' can still be found ...\n"
FOUND=$(grep -rio "$FIND" . | sed 's/:.*//g' | sed 's/^.\///g' | grep -v '^tmp' | grep -v '^.git' | grep -v 'Binary file' | uniq)
echo -e "\nfound: -------------- \n${FOUND}\n ---------------------\n"
